//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cheques.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SUNPLUSADV")]
        public string sunDatabase {
            get {
                return ((string)(this["sunDatabase"]));
            }
            set {
                this["sunDatabase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SUNPLUSSVR")]
        public string sunDatasource {
            get {
                return ((string)(this["sunDatasource"]));
            }
            set {
                this["sunDatasource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sa")]
        public string sunUser {
            get {
                return ((string)(this["sunUser"]));
            }
            set {
                this["sunUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SunPlus7!")]
        public string sunPassword {
            get {
                return ((string)(this["sunPassword"]));
            }
            set {
                this["sunPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A")]
        public string sunLibro {
            get {
                return ((string)(this["sunLibro"]));
            }
            set {
                this["sunLibro"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CEA")]
        public string sunUnidadDeNegocio {
            get {
                return ((string)(this["sunUnidadDeNegocio"]));
            }
            set {
                this["sunUnidadDeNegocio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("102")]
        public string sunEspacios1 {
            get {
                return ((string)(this["sunEspacios1"]));
            }
            set {
                this["sunEspacios1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string sunImpresionDirecta {
            get {
                return ((string)(this["sunImpresionDirecta"]));
            }
            set {
                this["sunImpresionDirecta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public string entersPrimeros1 {
            get {
                return ((string)(this["entersPrimeros1"]));
            }
            set {
                this["entersPrimeros1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("182")]
        public string espaciosDeFecha1 {
            get {
                return ((string)(this["espaciosDeFecha1"]));
            }
            set {
                this["espaciosDeFecha1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public string entersEntreFechaYNombre1 {
            get {
                return ((string)(this["entersEntreFechaYNombre1"]));
            }
            set {
                this["entersEntreFechaYNombre1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string entersEntreNombreYLetras1 {
            get {
                return ((string)(this["entersEntreNombreYLetras1"]));
            }
            set {
                this["entersEntreNombreYLetras1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("64")]
        public string espaciosEntreNombreYTotal1 {
            get {
                return ((string)(this["espaciosEntreNombreYTotal1"]));
            }
            set {
                this["espaciosEntreNombreYTotal1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("220")]
        public string leftCheque1 {
            get {
                return ((string)(this["leftCheque1"]));
            }
            set {
                this["leftCheque1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("52")]
        public string topCheque1 {
            get {
                return ((string)(this["topCheque1"]));
            }
            set {
                this["topCheque1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("420")]
        public string anchoCheque1 {
            get {
                return ((string)(this["anchoCheque1"]));
            }
            set {
                this["anchoCheque1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192")]
        public string largoCheque1 {
            get {
                return ((string)(this["largoCheque1"]));
            }
            set {
                this["largoCheque1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SUNPLUSCHEQUES")]
        public string DatabaseCheques {
            get {
                return ((string)(this["DatabaseCheques"]));
            }
            set {
                this["DatabaseCheques"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C")]
        public string letra {
            get {
                return ((string)(this["letra"]));
            }
            set {
                this["letra"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("102")]
        public string sunEspacios2 {
            get {
                return ((string)(this["sunEspacios2"]));
            }
            set {
                this["sunEspacios2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("102")]
        public string sunEspacios3 {
            get {
                return ((string)(this["sunEspacios3"]));
            }
            set {
                this["sunEspacios3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public string entersPrimeros2 {
            get {
                return ((string)(this["entersPrimeros2"]));
            }
            set {
                this["entersPrimeros2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public string entersPrimeros3 {
            get {
                return ((string)(this["entersPrimeros3"]));
            }
            set {
                this["entersPrimeros3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("182")]
        public string espaciosDeFecha2 {
            get {
                return ((string)(this["espaciosDeFecha2"]));
            }
            set {
                this["espaciosDeFecha2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("182")]
        public string espaciosDeFecha3 {
            get {
                return ((string)(this["espaciosDeFecha3"]));
            }
            set {
                this["espaciosDeFecha3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public string entersEntreFechaYNombre2 {
            get {
                return ((string)(this["entersEntreFechaYNombre2"]));
            }
            set {
                this["entersEntreFechaYNombre2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public string entersEntreFechaYNombre3 {
            get {
                return ((string)(this["entersEntreFechaYNombre3"]));
            }
            set {
                this["entersEntreFechaYNombre3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string entersEntreNombreYLetras2 {
            get {
                return ((string)(this["entersEntreNombreYLetras2"]));
            }
            set {
                this["entersEntreNombreYLetras2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string entersEntreNombreYLetras3 {
            get {
                return ((string)(this["entersEntreNombreYLetras3"]));
            }
            set {
                this["entersEntreNombreYLetras3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("64")]
        public string espaciosEntreNombreYTotal2 {
            get {
                return ((string)(this["espaciosEntreNombreYTotal2"]));
            }
            set {
                this["espaciosEntreNombreYTotal2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("64")]
        public string espaciosEntreNombreYTotal3 {
            get {
                return ((string)(this["espaciosEntreNombreYTotal3"]));
            }
            set {
                this["espaciosEntreNombreYTotal3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("220")]
        public string leftCheque2 {
            get {
                return ((string)(this["leftCheque2"]));
            }
            set {
                this["leftCheque2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("220")]
        public string leftCheque3 {
            get {
                return ((string)(this["leftCheque3"]));
            }
            set {
                this["leftCheque3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("52")]
        public string topCheque2 {
            get {
                return ((string)(this["topCheque2"]));
            }
            set {
                this["topCheque2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("52")]
        public string topCheque3 {
            get {
                return ((string)(this["topCheque3"]));
            }
            set {
                this["topCheque3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("420")]
        public string anchoCheque2 {
            get {
                return ((string)(this["anchoCheque2"]));
            }
            set {
                this["anchoCheque2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("420")]
        public string anchoCheque3 {
            get {
                return ((string)(this["anchoCheque3"]));
            }
            set {
                this["anchoCheque3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192")]
        public string largoCheque2 {
            get {
                return ((string)(this["largoCheque2"]));
            }
            set {
                this["largoCheque2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192")]
        public string largoCheque3 {
            get {
                return ((string)(this["largoCheque3"]));
            }
            set {
                this["largoCheque3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string campo {
            get {
                return ((string)(this["campo"]));
            }
            set {
                this["campo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ciudad {
            get {
                return ((string)(this["ciudad"]));
            }
            set {
                this["ciudad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string colonia {
            get {
                return ((string)(this["colonia"]));
            }
            set {
                this["colonia"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string calle {
            get {
                return ((string)(this["calle"]));
            }
            set {
                this["calle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public string fechaX1 {
            get {
                return ((string)(this["fechaX1"]));
            }
            set {
                this["fechaX1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public string fechaY1 {
            get {
                return ((string)(this["fechaY1"]));
            }
            set {
                this["fechaY1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public string fechaX2 {
            get {
                return ((string)(this["fechaX2"]));
            }
            set {
                this["fechaX2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public string fechaX3 {
            get {
                return ((string)(this["fechaX3"]));
            }
            set {
                this["fechaX3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public string fechaX4 {
            get {
                return ((string)(this["fechaX4"]));
            }
            set {
                this["fechaX4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public string fechaY2 {
            get {
                return ((string)(this["fechaY2"]));
            }
            set {
                this["fechaY2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public string fechaY3 {
            get {
                return ((string)(this["fechaY3"]));
            }
            set {
                this["fechaY3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public string fechaY4 {
            get {
                return ((string)(this["fechaY4"]));
            }
            set {
                this["fechaY4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public string nombreX1 {
            get {
                return ((string)(this["nombreX1"]));
            }
            set {
                this["nombreX1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public string nombreX2 {
            get {
                return ((string)(this["nombreX2"]));
            }
            set {
                this["nombreX2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public string nombreX3 {
            get {
                return ((string)(this["nombreX3"]));
            }
            set {
                this["nombreX3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public string nombreX4 {
            get {
                return ((string)(this["nombreX4"]));
            }
            set {
                this["nombreX4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("165")]
        public string nombreY1 {
            get {
                return ((string)(this["nombreY1"]));
            }
            set {
                this["nombreY1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("165")]
        public string nombreY2 {
            get {
                return ((string)(this["nombreY2"]));
            }
            set {
                this["nombreY2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("165")]
        public string nombreY3 {
            get {
                return ((string)(this["nombreY3"]));
            }
            set {
                this["nombreY3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("165")]
        public string nombreY4 {
            get {
                return ((string)(this["nombreY4"]));
            }
            set {
                this["nombreY4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("580")]
        public string cantidadX1 {
            get {
                return ((string)(this["cantidadX1"]));
            }
            set {
                this["cantidadX1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("580")]
        public string cantidadX2 {
            get {
                return ((string)(this["cantidadX2"]));
            }
            set {
                this["cantidadX2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("580")]
        public string cantidadX3 {
            get {
                return ((string)(this["cantidadX3"]));
            }
            set {
                this["cantidadX3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("580")]
        public string cantidadX4 {
            get {
                return ((string)(this["cantidadX4"]));
            }
            set {
                this["cantidadX4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("165")]
        public string cantidadY1 {
            get {
                return ((string)(this["cantidadY1"]));
            }
            set {
                this["cantidadY1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("165")]
        public string cantidadY2 {
            get {
                return ((string)(this["cantidadY2"]));
            }
            set {
                this["cantidadY2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("165")]
        public string cantidadY3 {
            get {
                return ((string)(this["cantidadY3"]));
            }
            set {
                this["cantidadY3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("165")]
        public string cantidadY4 {
            get {
                return ((string)(this["cantidadY4"]));
            }
            set {
                this["cantidadY4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public string letraX1 {
            get {
                return ((string)(this["letraX1"]));
            }
            set {
                this["letraX1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public string letraX2 {
            get {
                return ((string)(this["letraX2"]));
            }
            set {
                this["letraX2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public string letraX3 {
            get {
                return ((string)(this["letraX3"]));
            }
            set {
                this["letraX3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public string letraX4 {
            get {
                return ((string)(this["letraX4"]));
            }
            set {
                this["letraX4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("140")]
        public string letraY1 {
            get {
                return ((string)(this["letraY1"]));
            }
            set {
                this["letraY1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("140")]
        public string letraY2 {
            get {
                return ((string)(this["letraY2"]));
            }
            set {
                this["letraY2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("140")]
        public string letraY3 {
            get {
                return ((string)(this["letraY3"]));
            }
            set {
                this["letraY3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("140")]
        public string letraY4 {
            get {
                return ((string)(this["letraY4"]));
            }
            set {
                this["letraY4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("220")]
        public string leftCheque4 {
            get {
                return ((string)(this["leftCheque4"]));
            }
            set {
                this["leftCheque4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192")]
        public string largoCheque4 {
            get {
                return ((string)(this["largoCheque4"]));
            }
            set {
                this["largoCheque4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("52")]
        public string topCheque4 {
            get {
                return ((string)(this["topCheque4"]));
            }
            set {
                this["topCheque4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("420")]
        public string anchoCheque4 {
            get {
                return ((string)(this["anchoCheque4"]));
            }
            set {
                this["anchoCheque4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string predefinidoCheque {
            get {
                return ((string)(this["predefinidoCheque"]));
            }
            set {
                this["predefinidoCheque"] = value;
            }
        }
    }
}
