//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cheques.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SUNPLUSADV")]
        public string sunDatabase {
            get {
                return ((string)(this["sunDatabase"]));
            }
            set {
                this["sunDatabase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SUNPLUSSVR")]
        public string sunDatasource {
            get {
                return ((string)(this["sunDatasource"]));
            }
            set {
                this["sunDatasource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sa")]
        public string sunUser {
            get {
                return ((string)(this["sunUser"]));
            }
            set {
                this["sunUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SunPlus7!")]
        public string sunPassword {
            get {
                return ((string)(this["sunPassword"]));
            }
            set {
                this["sunPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A")]
        public string sunLibro {
            get {
                return ((string)(this["sunLibro"]));
            }
            set {
                this["sunLibro"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CEA")]
        public string sunUnidadDeNegocio {
            get {
                return ((string)(this["sunUnidadDeNegocio"]));
            }
            set {
                this["sunUnidadDeNegocio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("102")]
        public string sunEspacios {
            get {
                return ((string)(this["sunEspacios"]));
            }
            set {
                this["sunEspacios"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string sunImpresionDirecta {
            get {
                return ((string)(this["sunImpresionDirecta"]));
            }
            set {
                this["sunImpresionDirecta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public string entersPrimeros {
            get {
                return ((string)(this["entersPrimeros"]));
            }
            set {
                this["entersPrimeros"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("182")]
        public string espaciosDeFecha {
            get {
                return ((string)(this["espaciosDeFecha"]));
            }
            set {
                this["espaciosDeFecha"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public string entersEntreFechaYNombre {
            get {
                return ((string)(this["entersEntreFechaYNombre"]));
            }
            set {
                this["entersEntreFechaYNombre"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string entersEntreNombreYLetras {
            get {
                return ((string)(this["entersEntreNombreYLetras"]));
            }
            set {
                this["entersEntreNombreYLetras"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("64")]
        public string espaciosEntreNombreYTotal {
            get {
                return ((string)(this["espaciosEntreNombreYTotal"]));
            }
            set {
                this["espaciosEntreNombreYTotal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("220")]
        public string leftCheque {
            get {
                return ((string)(this["leftCheque"]));
            }
            set {
                this["leftCheque"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("52")]
        public string topCheque {
            get {
                return ((string)(this["topCheque"]));
            }
            set {
                this["topCheque"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("420")]
        public string anchoCheque {
            get {
                return ((string)(this["anchoCheque"]));
            }
            set {
                this["anchoCheque"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192")]
        public string largoCheque {
            get {
                return ((string)(this["largoCheque"]));
            }
            set {
                this["largoCheque"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SUNPLUSCHEQUES")]
        public string DatabaseCheques {
            get {
                return ((string)(this["DatabaseCheques"]));
            }
            set {
                this["DatabaseCheques"] = value;
            }
        }
    }
}
